swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: View Monthly Transactions
      description: API to retrieve all transactions for the current month, grouped by account
      produces:
        - application/json
      responses:
        '200':
          description: Monthly transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: View Transaction Details
      description: API to view details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: ID of the transaction to retrieve
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction
      description: API to update information about a specific transaction (only category and note can be modified)
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: ID of the transaction to update
        - in: body
          name: body
          description: Transaction update payload
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  TransactionsResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
      accountId:
        type: string
        description: Account ID the transactions are grouped by
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
      date:
        type: string
      description: 
        type: string
      amount:
        type: number
      balance: 
        type: number
      transaction type: 
        type: string
      category:
        type: string
      note:
        type: string
        description: Optional note for the transaction
  TransactionDetailsResponse:
    type: object
    properties:
      transaction:
        $ref: '#/definitions/Transaction'
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      note:
        type: string